
    EQUIPE	E04	

    COMPONENTES:     

    Nome	Email	Telefone

    Rafael Bessa Loureiro	xxx	xxx

    Pedro De Carvalho Marcelo	xxxxx	xxx

    Neilton Melgaço Lisboa Junior	xxx	xxx

    
tipo, Elemento lexico , Codigo , indicie tabela simb , linha  
Int , Int , 323 , none , 0
function , batata , 513 , 600 , 0
igual , = , 419 , none , 0
floatNum , 3.5 , 512 , 601 , 0
function , float , 513 , 602 , 0
function , bb , 513 , 603 , 0
igual , = , 419 , none , 0
floatNum , 12.21e3 , 512 , 604 , 0
function , a_0 , 513 , 605 , 1
character , 'a' , 510 , 606 , 1
Program , Program , 321 , none , 1
If , If , 324 , none , 1
abreparentese , ( , 412 , none , 1
fechaparentese , ) , 423 , none , 1
Bool , Bool , 310 , none , 2
Bool , Bool , 310 , none , 2
igualigual , == , 430 , none , 2
constantString , "stringtest" , 511 , 607 , 2
mais , + , 417 , none , 2
menos , - , 432 , none , 2
igual , = , 419 , none , 3
If , If , 324 , none , 3
abreparentese , ( , 412 , none , 3
menos , - , 432 , none , 3
intergerNum , 5 , 515 , 608 , 3
fechaparentese , ) , 423 , none , 3
Bool , Bool , 310 , none , 3
Bool , Bool , 310 , none , 3
igualigual , == , 430 , none , 3
mais , + , 417 , none , 3
menos , - , 432 , none , 3
igual , = , 419 , none , 3
If , If , 324 , none , 4
abreparentese , ( , 412 , none , 4
fechaparentese , ) , 423 , none , 4
Bool , Bool , 310 , none , 4
Bool , Bool , 310 , none , 4
igualigual , == , 430 , none , 4
mais , + , 417 , none , 4
menos , - , 432 , none , 4
igual , = , 419 , none , 4
While , While , 311 , none , 4
Int , Int , 323 , none , 5
